# Enables necessary Apache modules and disables websites.
-   name: enable-modules
    command: a2enmod {{ item }} creates=/etc/apache2/mods-enabled/{{ item }}.load
    with_items:
        - wsgi
        - headers
        - expires
        - rewrite
        - ssl
    notify: restart-apache

-   name: disable-sites
    command: a2dissite {{ item }} removes=/etc/apache2/sites-enabled/{{ item }}
    with_items:
        - default
    notify: restart-apache

-   name: apache-http-conf
    copy: src=httpd.conf dest=/etc/apache2/httpd.conf owner=root group=root mode=0644
    notify:
        - restart-apache
    tags:
        - apache-conf

-   name: apache-ports-conf
    copy: src=ports.conf dest=/etc/apache2/ports.conf owner=root group=root mode=0644
    notify:
        - restart-apache
    tags:
        - apache-conf

# Make sure the web server is running.
-   name: apache2-started
    service: name=apache2 state=started enabled=yes
